backend:
  name: github
  repo: vanbichha/decap-tutorial
  branch: main
  base_url: https://decap-oauth.vanbichha-vh.workers.dev
  auth_endpoint: auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }